# Generated by Django 5.1.7 on 2025-03-16 04:37

from django.db import migrations

def insert_holidays(apps, schema_editor):
    Timeslot = apps.get_model('timeschedulingweb', 'Timeslot')
    Timeslot('start_time = 2025-14-03T00:00:00',
             'end_time = 2025-14-03T23:59:59',
             description= 'Holi').save()
    Timeslot('start_time = 2025-15-08T00:00:00',
             'end_time = 2025-15-08T23:59:59',
             description= 'Independence Day').save()
    Timeslot('start_time = 2025-02-10T00:00:00',
             'end_time = 2025-02-10T23:59:59',
             description= 'Gandhi Jayanti').save()
class Migration(migrations.Migration):
    dependencies = [
        ('timeschedulingweb', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(insert_holidays)
    ]
