# Generated by Django 5.1.7 on 2025-03-16 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeschedulingweb', '0002_insert_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('time_slot', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='timeschedulingweb.timeslot')),
            ],
        ),
    ]
